import express, { json, urlencoded, Request, Response } from 'express'
import { RegisterRoutes } from '../generated/routes'
import swaggerUi from 'swagger-ui-express'

const PORT = process.env.PORT ?? 3000

const app = express()

app.use(
  urlencoded({
    extended: true,
  })
)
app.use(json())

// register REST api routes generated by `tsoa`
RegisterRoutes(app)

app.get('/healthcheck', (_req, res) => {
  res.end('ok')
})

// serve auto-generated documentation for REST api at /docs
app.use('/docs', swaggerUi.serve, async (_req: Request, res: Response) => {
  return res.send(
    swaggerUi.generateHTML(await import('../generated/swagger.json'))
  )
})

app.listen(PORT, () =>
  console.log(`Server listening at http://localhost:${PORT}`)
)
